repos:
- repo: local
  hooks:
    - id: pycln
      name: pycln
      entry: pycln --config pyproject.toml
      language: system
    - id: isort
      name: isort
      entry: isort
      language: system
      files: \.py$
      exclude: ^tvl/api/l2_api.py$|^tvl/api/l3_api.py$|^tvl/targets/model/configuration_object_impl.py$
    - id: black
      name: black
      entry: black
      language: system
      files: \.py$
      exclude: ^tvl/api/l2_api.py$|^tvl/api/l3_api.py$|^tvl/targets/model/configuration_object_impl.py$