on:
  release:
    types: [created]

jobs:
  build:
    name: Build and Upload Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Cache virtual environment
        uses: actions/cache@v4
        with:
          key: venv-${{ runner.os }}-${{ steps.setup_python.outputs.python-version}}-${{ hashFiles('poetry.lock') }}
          path: .venv
      - name: install dependencies
        run: |
            python3.8 -m venv .venv
            source .venv/bin/activate
            pip install --upgrade pip
            pip install poetry
            poetry config virtualenvs.in-project true
            poetry install --no-root --no-interaction --with=dev
            echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
            echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
      - name: Build Wheel
        run: poetry build -f wheel
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ts-tvl-package
          path: dist/*.whl
